### ISSUE TITLE
sol/17-3.cpp で変数・コメントのAnswer1,2がeditorialと逆に見えます

### ISSUE THREAD

**Issue by MoSooN1110** [E869120/kyopro_educational_90#18]
## 典型17の解説とソースコードでAnswer#の割り振りが異なっているように見えました。
解説のAnswer1が下記実装に対応し
```c
	// Step #3. Get Answer2
	long long Answer2 = 0;
	for (int i = 1; i <= M; i++) V3[L[i]] += 1;
	for (int i = 1; i <= M; i++) V3[R[i]] += 1;
	for (int i = 1; i <= N; i++) Answer2 += V3[i] * (V3[i] - 1LL) / 2LL;
```

解説のAnswer2が下記実装に対応すると思います。
```c
	// Step #2. Get Answer1
	long long Answer1 = 0;
	for (int i = 1; i <= M; i++) V1[R[i]] += 1;
	for (int i = 1; i <= M; i++) V2[L[i] - 1] += 1;
	for (int i = 1; i <= N; i++) V1[i] += V1[i - 1];
	for (int i = 1; i <= N; i++) Answer1 += V1[i] * V2[i];
```

17-2.cpp も同様だと思います。

## ref
cpp
[url]https://github.com/E869120/kyopro_educational_90/blob/main/sol/017-03.cpp

editorial
[url]https://github.com/E869120/kyopro_educational_90/blob/main/editorial/017-02.jpg

**Comment by E869120** [comment]
ご指摘いただきありがとうございます！
017-02.cpp / 017-03.cpp を解説と合うように修正しました。

* [017-02.cpp のリンク](https://github.com/E869120/kyopro_educational_90/blob/main/sol/017-02.cpp)
* [017-03.cpp のリンク](https://github.com/E869120/kyopro_educational_90/blob/main/sol/017-03.cpp)
