### ISSUE TITLE
典型068の解説が一部間違っている

### ISSUE THREAD

**Issue by peroon** [E869120/kyopro_educational_90#19]
https://twitter.com/peroon_cp/status/1409527756132544520

こちらでも指摘したのですが、本にもなるということでもう1度連絡してみます。

典型068にて、問題文では
Ti=0 or 1なのですが、
解説では
Ti=1 or 2となっていて、制約が一致していません。

**Comment by E869120** [comment]
ご指摘いただきありがとうございました。
解説を T[i] ∈ {0, 1} に修正しました。対応が遅くなり申し訳ございません。
