### ISSUE TITLE
42 の解説

### ISSUE THREAD

**Issue by noriok** [E869120/kyopro_educational_90#20]
https://github.com/E869120/kyopro_educational_90/blob/main/editorial/042.jpg

解説右側の記述ですが、
誤: `9 の倍数: 各桁の数字の和が 3 の倍数`
正: `9 の倍数: 各桁の数字の和が 9 の倍数`
だと思います。

**Comment by E869120** [comment]
こんにちは、E869120 です。対応が遅れてしまい申し訳ございません。

問題 042 の解説を修正しました。GitHub では反映されていると思いますが、確認お願いします。

**Comment by noriok** [comment]
修正を確認しました。対応ありがとうございました。

(典型90 お疲れ様でした！とても楽しかったです。)
