### ISSUE TITLE
問題 06 の解説の類題

### ISSUE THREAD

**Issue by fumuumuf** [E869120/kyopro_educational_90#21]
素晴らしい企画ありがとうございます。

問題 06 の解説にある、類題の２つめ [辞書式順序ふたたび](https://atcoder.jp/contests/abc009/tasks/abc009_3) の問題番号が間違ってそうです。正しくは `ABC009-C` と思われます。

https://github.com/E869120/kyopro_educational_90/blob/main/editorial/006.jpg

**Comment by E869120** [comment]
こんにちは、E869120 です。対応が遅れてしまい申し訳ございません。

GitHub で問題番号を修正しました。確認お願いします。

**Comment by ghost** [comment]
確認しました！ 修正ありがとうございました:bow:
